### ISSUE TITLE
OpenGL.error.GLError

### ISSUE THREAD

**Issue by Kana-alt** [google/lasr#5]
I set up an environment in docker and tried to run the rendering code.

As a result, I got an OpenGL error. Is this due to a different version installed or something else?

"""
docker run -v $(pwd):/lasr --gpus all lasr bash -c 'cd lasr; source activate lasr; python render_vis.py --testdir log/spot3-1/ --seqname spot3 --freeze --outpath tmp/1.gif'

log/spot3-1/
syn-spot3f/0
syn-spot3f/1
0
Traceback (most recent call last):
  File "render_vis.py", line 292, in <module>
    main()
  File "render_vis.py", line 226, in main
    r = OffscreenRenderer(img_size, img_size)
  File "/anaconda3/envs/lasr/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/anaconda3/envs/lasr/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/anaconda3/envs/lasr/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 186, in init_context
    self._egl_context = eglCreateContext(
  File "/anaconda3/envs/lasr/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/anaconda3/envs/lasr/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
	err = 12297,
	baseOperation = eglCreateContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f1e16d3a1c0>,
		<OpenGL._opaque.EGLConfig_pointer object at 0x7f1e16d3a240>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f1e16d85040>,
		<OpenGL.arrays.lists.c_int_Array_7 object at 0x7f1e2fd5a940>,
	),
	result = <OpenGL._opaque.EGLContext_pointer object at 0x7f1e16d3a8c0>
)
"""

**Comment by gengshan-y** [comment]
Hi, I do not remember that we came across this issue in previous testings. I'll do another one in the next few days. 
Does this help? https://github.com/mmatl/pyrender/issues/86#issuecomment-767613647

In the worse case scenario, you could use anaconda for rendering.

**Comment by Kana-alt** [comment]
Thank you.
I tried to modify it based on this site, but it did not work.

I was able to successfully render in the Anaconda environment.

**Comment by gengshan-y** [comment]
Just tried again and the docker image worked fine for me. Closing it for now.
